project:
  type: website

website:
  title: Project Title
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-Fall25-101-201/final-project-spencer-atchley-solo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
